# Generated by Django 4.1.3 on 2022-11-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_vagas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='tecnologia',
            new_name='tecnologias',
        ),
    ]
